import { timingSafeEqual } from "node:crypto";
import express, { Router, type Request, type Response } from "express";
import {
  parseSnsEnvelope,
  parseSesEvent,
  suppressionFor,
  bounceReasonFor,
  type ParsedEmailEvent,
} from "../newsletter/ses-events";
import { recordEmailEvent, countBounces } from "../db/newsletter-events";
import { suppressEmail } from "../db/email-suppressions";
import { markEmailDelivery } from "../db/email-log";
import { config } from "../config";

// The SES delivery webhook (Resend→SES migration; TASK-255 lineage — see
// docs/superpowers/specs/2026-07-16-newsletter-email-stats-design.md). SES publishes an event to
// an SNS topic for every email sent through a configuration set; SNS POSTs each one here and we
// keep only the ones that match a newsletter send.
//
// Trust boundary: this URL is public, and these events are the ONLY writer of delivery facts.
// The secret token in the path is everything — the role the Svix signing secret played for the
// Resend webhook, and Stripe's constructEvent plays for donations. It is generated by Terraform
// (random_password → SSM SES_WEBHOOK_TOKEN → both this app and the SNS subscription endpoint
// URL), compared timing-safely, and never logged. The SubscriptionConfirmation handshake is
// auto-confirmed, but ONLY for https URLs on a real sns.<region>.amazonaws.com host
// (parseSnsEnvelope enforces that), so nobody can use this endpoint to make us GET their server.
//
// Response discipline (SNS retries anything non-2xx):
//   503 — token not configured yet (deploy precedes the infra apply that mints it; a retry later
//         may genuinely succeed, so retrying is CORRECT);
//   401 — wrong token: not our SNS subscription, go away;
//   200 — everything else, INCLUDING events we drop (unconsumed types, receipts/login codes that
//         match no newsletter send, duplicates). Anything but a 2xx would make SNS hammer us
//         with retries for data we never wanted.
// How many bounces of ANY kind before an address is treated as dead. Three is late enough that a
// provider outage does not cost a supporter, and early enough that we are not the sender still
// hammering a dead mailbox months later.
const REPEAT_BOUNCE_LIMIT = 3;

// The short human-readable reason stored beside a bounce/complaint on the audit page: the
// provider's diagnostic where it gave one, else the bounce sub-type; null for a clean delivery.
function deliveryDetailOf(event: ParsedEmailEvent): string | null {
  return event.eventType === "bounced" ? bounceReasonFor(event) : null;
}

export const sesWebhookRouter = Router();

function tokenMatches(offered: string): boolean {
  const expected = Buffer.from(config.SES_WEBHOOK_TOKEN);
  const given = Buffer.from(offered);
  return expected.length === given.length && timingSafeEqual(expected, given);
}

async function postSesWebhook(req: Request, res: Response): Promise<Response> {
  if (!config.SES_WEBHOOK_TOKEN) {
    return res.status(503).json({ error: "Webhook not configured" });
  }
  if (!tokenMatches(req.params.token ?? "")) {
    return res.status(401).json({ error: "Invalid token" });
  }

  const rawBody = (req.body as Buffer).toString("utf8");
  const envelope = parseSnsEnvelope(rawBody);
  if (!envelope) return res.status(200).json({ outcome: "ignored" });

  if (envelope.type === "SubscriptionConfirmation") {
    // One-time handshake when the SNS subscription is (re)created. parseSnsEnvelope has already
    // pinned the URL to https + a genuine SNS host.
    try {
      await fetch(envelope.subscribeUrl);
      return res.status(200).json({ outcome: "confirmed" });
    } catch (err) {
      console.error("SNS subscription confirm failed:", err instanceof Error ? err.message : err);
      return res.status(500).json({ error: "Confirmation failed" }); // SNS re-delivers; retry is right
    }
  }

  const parsed = parseSesEvent(envelope.message);
  if (!parsed) return res.status(200).json({ outcome: "ignored" });

  // TASK-464: one email can go to several people (the Ball's ticket report), and SES names the
  // people each event is about. Everything below happens once for each person named, so a bounce
  // from one of them never lands on, or suppresses, another. Every other email has one person.
  const people: ParsedEmailEvent[] = parsed.recipients.map((email) => ({ ...parsed, email }));

  // Email-audit enrichment: stamp the mailbox-side outcome onto the newest matching email_log
  // row (src/db/email-log.ts). Best-effort and FIRST, so a failure in the newsletter recording
  // below cannot cost the audit page its delivery truth (and vice versa — each is independent).
  if (parsed.eventType === "delivered" || parsed.eventType === "bounced" || parsed.eventType === "complained") {
    for (const one of people) {
      try {
        // TASK-346: the message id makes this land on the exact send. Null for an email sent
        // before that shipped, in which case markEmailDelivery falls back to the old
        // recipient-and-recency guess rather than dropping the outcome.
        await markEmailDelivery(one.email, parsed.eventType, one.occurredAt, deliveryDetailOf(one), one.messageId);
      } catch (err) {
        console.error("email log delivery stamp failed:", err instanceof Error ? err.message : err);
      }
    }
  }

  try {
    const outcomes: string[] = [];
    for (const [i, one] of people.entries()) {
      // The first person keeps SNS's own id, exactly as before; anyone after gets their own, so an
      // SNS retry of the same notification is still a duplicate for each of them.
      outcomes.push(await recordEmailEvent(i === 0 ? envelope.messageId : `${envelope.messageId}:${i}`, one));
      // TASK-272 lineage: a complaint or a PERMANENT bounce takes the address out of every future
      // send. This runs even when the event matched no newsletter (outcome 'unmatched') — the
      // address is just as dead whether or not we can tie the bounce to a particular send, and a
      // big send can outrun the correlation window. Suppression is independent of attribution on
      // purpose.
      const suppression = suppressionFor(one);
      if (suppression) {
        await suppressEmail(one.email, suppression.reason, suppression.detail);
      } else if (one.eventType === "bounced") {
        // TASK-277 (letter R): a transient bounce does not suppress on its own — a full mailbox is
        // temporary. But an address that keeps bouncing is dead in practice whatever the provider
        // calls it, and mailing it forever is what damages a sender's reputation. Repetition is the
        // signal.
        const bounces = await countBounces(one.email);
        if (bounces >= REPEAT_BOUNCE_LIMIT) {
          await suppressEmail(one.email, "bounced", `bounced ${bounces} times`);
        }
      }
    }
    return res.status(200).json({ outcome: outcomes.join(",") });
  } catch (err) {
    // A DB hiccup is worth a retry from SNS's side — this is the one path where 500 is right.
    console.error("ses webhook recording failed:", err instanceof Error ? err.message : err);
    return res.status(500).json({ error: "Event recording failed" });
  }
}

// SNS sends Content-Type text/plain for its JSON payloads, so accept ANY type raw on this path.
sesWebhookRouter.post(
  "/api/webhooks/ses/:token",
  express.raw({ type: () => true }),
  postSesWebhook,
);
